language: php
php:
- '5.6'
- '7.0'
install:
- composer install
services:
- mysql
dist: trusty
sudo: required
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
before_script:
- sudo apt-get install apache2 libapache2-mod-fastcgi
- sudo service apache2 restart
- mysql -uroot -e "create database IF NOT EXISTS joomla;"
- mysql -uroot joomla < libraries/zoolanders/vendor/zoolanders/framework-test-env/db/joomla.sql
script:
- nvm install node
- npm install
- composer install
- npm run build
after_success:
    "curl -T dist/*.zip -u $FTP_USER:$FTP_PASSWORD ftp://www.zoolanders.com/framework/"
notifications:
  email: false
branches:
  only:
  - master
  - develop
env:
  global:
    - secure: aumWyo+Yt1S/FjRbyNg4LwEDLpp7SaBMf2S9bjclvZPB45mSJ602Em8T6If8hJk447mBILyxtu8nSyKdmpkLawj4rOgyf2Iplvd4LPmWAeacFogZFkVhwaTihwx6kbmpSruICEQtXYOZeNJjwP6O0+HQoRwxu906otAz++ABRP4vfyMrj6ILXqffWi16AyuLvmYH8r0lEoVXDEMjD9kGupMBnxUMls1uBSiG1g2xInsbNHODsgoL7/qGgI+2AjuN2vfENOeSnAjZBFcNwAgVTONBZk7qnu/2vc2ELJ9biiM+906sKIP/c7UrrFmxiDZYNloOdPTUMl+hX5KGxryc95uo7K+MvSoYFot3FJFmuHVm3Uvec7y48gQw+ka99ezCIdvysvQiGigdtWzAOq+1fL7F8LFEVejb+nbfYiWUhta7zv/gcnFrEaWlnH0L/6PJKiMDxgZQlTslZ31t/ImxwITHv+pAoLz2AnoCWEGUl3OiZlNYWDoRU53wFBJNyBpMkWhd8roBUnA975W1Cw5MVuEfuoW1zyU4erxkuVu1IJvjWCVkYcbuyohNo4pvlDoC/9LeznuJs2ZgFt6yjdFdHYH/bzYCYjllWO7Tg66ajSPV/QL7KAteUd+VocBGoUnQfMoXs+gTjaO5t6Zhx9hMUEr3FlVFxSaKf2Wf/MQsEVc=
    - secure: aJu9C1Slsa70EwbksrRKjTJXg8zotUrieG17JDGC2ZS1BHh9iulciqPwGb6G1d4xVOFjaO5iyVjqsSMj17avLuFC7BqE/JY3okTk3Fa/LRkGHRl/g+vjkXLWImcGHBPL/HD8BTV2TzCNZ85rhgNXVue5Ubm9UXCbfYoGguD9EKoQJfyDPEg5MkRjTZdnICofWUafj3u9BPkxlQmuoRlZ3JFfqe4f7lHaSB9XRCJgRjMhP8htiL78Vu6dhPoPgGUgF1nWP3ax0kHHpU2lNTBhTVIr6jggcrbUU2VfMVVAbwy+21V24PaMxmQJ2xNikHQVAzOTRv1wm7C/JOJX9gtC6zbUWxXCChoVJiVoOKIjco3z+Vb6Gk122FIXkPUkWT2iDVoMoDXKVqQ0dLn+QEmupdLiZ2uz1Qk67Wsf+Okq3ZBJmiRLUaYZy13POfYSufEh2djQInqomPmETR4xuvCIvyQ+LNbX29x2+z2Zlubk6qSkm87637axQqeoBVBvFFRaHc5tmFb7DrywiRjUDIvPXPbs7c70jJ17X6TBcKVxorKDdpbqYtOOtbEb4QPZRP7GTMuCYHNtwggdK/crSl4aBUoDoAIXwVrGEx+1khC8GM23xM26FYQuUObIzVEq5+NPvpQl8ycLrQ+OGziJh/T7y1HWlFNjHLeYfkxgBpsomPc=