version: '3.1'

services:
  zoolanders:
    image: zoolanders
    restart: always
    links:
      - zoolanders-db:mysql
    ports:
      - 8080:80
    environment:
      JOOMLA_DB_HOST: zoolanders-db
      JOOMLA_DB_PASSWORD: root
    volumes:
      - ./src/libraries/zoolanders:/var/www/html/libraries/zoolanders
      - ./src/plugins/system/zlframework:/var/www/html/plugins/system/zlframework
      - ./src/administrator/language/en-GB/en-GB.plg_system_zlframework.ini:/var/www/html/administrator/language/en-GB/en-GB.plg_system_zlframework.ini
      - ./src/administrator/language/en-GB/en-GB.plg_system_zlframework.sys.ini:/var/www/html/administrator/language/en-GB/en-GB.plg_system_zlframework.sys.ini

  zoolanders-db:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
